provisioningAnnotations: &provisioningAnnotations
  helm.sh/hook-weight: "-4"
postgresql: &postgresql
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 11.14.0-debian-10-r49
  fullnameOverride: postgresql
  host: postgresql
  port: 5432
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations
  persistence:
    size: 25Gi
  databases:
  - name: "kong"

global:
  postgresql: *postgresql

migration:
  postgresql:
    waitTime: 120
