provisioningAnnotations: &provisioningAnnotations
  "helm.sh/hook-weight": "-4"

postgresql: &postgresql
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 11.14.0-debian-10-r49
  fullnameOverride: postgresql
  host: postgresql
  port: 5432
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations
  persistence:
    size: 25Gi
  databases:
  - name: "kong"

redis: &redis
  enabled: true
  nameOverride: "redis"
  fullnameOverride: "redis"
  auth:
    enabled: false
  host: "redis-master"
  port: 6379
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  replica:
    replicaCount: 0
  master:
    persistence:
      size: 25Gi

global:
  postgresql: *postgresql
  redis: *redis
